version: '2'
services:
  base:
    image: node:10-buster
    volumes:
    - ./glossaire-app:/usr/src/service
    - ./glossaire_app/node_modules:/usr/src/service/node_modules
    working_dir: /usr/src/service

  install:
    extends:
      service: base
    command: bash -c "npm install"
    

  fix:
    extends:
      service: base
    command: npm audit fix
  
  build:
    extends:
      service: base
    command: npm run build
  
  
